actualizacion de archivo yaml

diff --git a/.github/worflows/bigdata.yaml b/.github/worflows/bigdata.yaml
--- a/.github/worflows/bigdata.yaml
+++ b/.github/worflows/bigdata.yaml
@@ -18,7 +18,7 @@ jobs:
       - name: 2. Configurar Entorno Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.10"
+          python-version: "3.14"
 
       - name: 3. Instalar Dependencias Requeridas
         run: |
@@ -26,29 +26,29 @@ jobs:
           if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests pandas openpyxl; fi
 
       - name: 4. Ejecutar Script de Ingesta ETL
-        run: python ingestion.py
+        run: python ./src/ingestion.py
 
       - name: 5. Verificar Creación de BDD y Archivos de Evidencia
         run: |
           echo "=== VERIFICANDO EXISTENCIA DE ARTEFACTOS ==="
           
           # Validación de Base de Datos SQLite
-          if [ -f "data/db_cobertura_movil.db" ]; then
-            echo "[OK] Base de datos 'data/db_cobertura_movil.db' creada exitosamente."
+          if [ -f "src/static/db/ingestion.db" ]; then
+            echo "[OK] Base de datos 'src/static/db/ingestion.db' creada exitosamente."
           else
-            echo "[ERROR] No se encontró la base de datos SQLite." && exit 1
+            echo "[ERROR] No se encontró la base de datos SQL Server." && exit 1
           fi
 
           # Validación del Archivo de Muestra (Excel/CSV)
-          if [ -f "src/static/auditoria/ingestion.xlsx" ] || [ -f "output/muestra_representativa_cobertura.csv" ]; then
-            echo "[OK] Archivo de muestra generado correctamente en carpeta 'output/'."
+          if [ -f "src/static/auditoria/ingestion.xlsx" ] || [ -f "src/static/auditoria/ingestion.csv" ]; then
+            echo "[OK] Archivo de muestra generado correctamente en carpeta 'src/static/auditoria/'."
           else
             echo "[ERROR] No se encontró el archivo de muestra." && exit 1
           fi
 
           # Validación del Archivo de Auditoría (.txt)
-          if [ -f "output/auditoria_ingesta.txt" ]; then
-            echo "[OK] Archivo de auditoría 'output/auditoria_ingesta.txt' generado correctamente."
+          if [ -f "src/static/auditoria/auditoria_ingesta.txt" ]; then
+            echo "[OK] Archivo de auditoría 'src/static/auditoria/auditoria_ingesta.txt' generado correctamente."
           else
             echo "[ERROR] No se encontró el archivo de auditoría." && exit 1
           fi
@@ -58,6 +58,6 @@ jobs:
         with:
           name: evidencias-etl-cobertura
           path: |
-            output/
-            data/db_cobertura_movil.db
+            src/static/auditoria/
+            src/static/db/ingestion.db
           retention-days: 14
